version: '3.8'

services:
  config-server:
    build: ./ConfigurationServer
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: secretKey
      SPRING_PROFILES_ACTIVE: native
    networks:
      backend:
        aliases:
          - "config-server"

  licensing-service:
    build: ./LicensingService
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8071
    depends_on:
      licensing-service-db:
        condition: service_healthy
      config-server:
        condition: service_started
      kafka-server:
        condition: service_started
    networks:
      backend:
        aliases:
           - "licensing-service"

  organization-service:
    build: ./OrganizationService
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8071
    depends_on:
      organization-service-db:
        condition: service_healthy
      config-server:
        condition: service_started
      kafka-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "organization-service"

  eureka-server:
    build: ./EurekaServer
    ports:
      - "8070:8070"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8071
    networks:
      backend:
        aliases:
          - "eureka-server"

  gateway-server:
    build: ./GatewayServer
    ports:
      - "8083:8083"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8071
    depends_on:
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway-server"

  organization-service-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: organization-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - organization-service-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        aliases:
          - "organization-service-db"

  licensing-service-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: licensing-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - licensing-service-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        aliases:
          - "licensing-service-db"

  redis-server:
    image: redis:alpine
    ports:
      - "6739:6739"
    networks:
      backend:
        aliases:
          - "redis-server"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      backend:
        aliases:
          - "zookeeper"

  kafka-server:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: dresses:1:1,ratings:1:1
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    depends_on:
      zookeeper:
        condition: service_started
    volumes:
      - kafka-server-data:/kafka/kafka-logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
          - "kafka"

networks:
  backend:
    driver: bridge

volumes:
  licensing-service-data:
  organization-service-data:
  kafka-server-data: