server:
  port: 8083
eureka:
  instance:
    preferIpAddress:
      true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:
        http://eureka-server:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true